# kubernetes frontend deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-frontend
  namespace: rest-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-frontend
  template:
    metadata:
      labels:
        app: rest-frontend
    spec:
      containers:
        - name: rest-frontend
          image: ghenac/rest-2-client:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
