# kubernetes frontend service 

apiVersion: v1
kind: Service
metadata:
  name: rest-frontend
  namespace: rest-ns
spec:
  selector:
    app: rest-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
